export enum Routes {
    LandingPage = "/",
    Quiz = "/quiz",
    QuizDetails = "/quizzes/:id",
    Quizzes = "/quizzes",
    Login = "/login",
    faq = "/faq",
    Auth = "/auth/lookup",
    Signup = "/signup",
    Questions = "/questions",
    Answers = "/answers",
    AdminBase = "/admin",
    Dashboard = "/admin/dashboard",
    AdminQuestions = "/admin/questions",
    AdminQuestionDetails = "/admin/questions/:id",
    AdminFeedback = "/admin/feedback",
    Feedback = "/feedback",
    CreateQuestion = "/admin/questions/create",
    AdminUsers = "/admin/users",
    MyQuizzes = "/my-quizzes",
    AdminUserDetails = "/admin/users/:id",
    CreateUser = "/admin/users/create",
    Contacts = '/contacts',
    About = '/about'
}
