export enum Routes {
    LandingPage = "/",
    Quiz = "/quiz",
    Login = "/login",
    faq = "/faq",
    Auth = "/auth/lookup",
    Signup = "/signup",
    Dashboard = "/dashboard",
    Questions = "/questions",
    AdminQuestions = "/admin/questions",
    AdminQuestionDetails = "/admin/questions/:id",
    CreateQuestion = "/admin/questions/create",
    AdminUsers = "/admin/users",
    AdminUserDetails = "/admin/users/:id",
    CreateUser = "/admin/users/create",
}
